version: '3.8'

services:
  laravel:
    build: ./backend
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    command: bash -c "php artisan serve --host=0.0.0.0 --port=8000"
    depends_on:
      - mysql

  nextjs:
    build: ./frontend
    container_name: next_app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: bash -c "npm install && npm run dev"

  mysql:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
